const CLIENT_TO_DEVICE_REDDIS_CHANNEL = "client_to_device"
const DEVICE_TO_CLIENT_REDDIS_CHANNEL = "device_to_client"
const WSTOKEN_EXCHANGE_REDDIS_CHANNEL = 'wstoken_exchange'


module.exports = {
    CLIENT_TO_DEVICE_REDDIS_CHANNEL,
    DEVICE_TO_CLIENT_REDDIS_CHANNEL,
    WSTOKEN_EXCHANGE_REDDIS_CHANNEL
}
